services:
  postgres:
    build:
      context: ./containers/postgres
    env_file: ./containers/postgres/postgres.env
    volumes: 
      - pgdatax:/var/lib/postgresql/data
    ports: 
     - 5432:5432
    container_name: postgresdb

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./containers/pgadmin/pgadmin.env
    restart: unless-stopped
    container_name: administrator

volumes:
  pgdatax:
    external: true
